FROM tomee
COPY /web-task-manager.war /usr/local/tomee/webapps
COPY /context.xml /usr/local/tomee/conf
COPY /server.xml /usr/local/tomee/conf
COPY /mysql-connector-java-8.0.20.jar /usr/local/tomee/lib